# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grocery App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grocery App
  pod 'Firebase/Core'
  target 'Grocery AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Grocery AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
